import os
import sys

header_comment = """
/*
  Header file generated by PGGKBin2h
*/

"""

def getSize(fileobject):
    fileobject.seek(0,2) # move the cursor to the end of the file
    size = fileobject.tell()
    fileobject.seek(0,0)
    return size

if __name__ == '__main__':
    file = open(sys.argv[1], "rb")
    var_declaration = "const unsigned char "
    var_size_declaration = "const unsigned int "
    sys.argv[1] = sys.argv[1].replace("\\", "/");
    sys.argv[2] = sys.argv[2].replace("\\", "/");
    var_name = sys.argv[1].split("/")[-1].replace(".","_")
    tmpsize = getSize(file)
    tmpstr = header_comment + var_declaration + var_name + "[" + str(tmpsize) + "] = {"
    byte = file.read(1)
    while byte:
        tmpstr += "0x" + byte.hex()+","
        byte = file.read(1)
    tmpstr += "};"
    tmpstr = tmpstr.replace(",}", "}")
    tmpstr += "\n\n" +  var_size_declaration + var_name + "_size = " +str(tmpsize) + ";"
    f = open(sys.argv[2], "w")
    f.write(tmpstr)
    f.close()
    file.close()
